name: 'Squash Merge Action'
description: 'Performs squash merge from source branch to target branch across multiple repositories'
author: 'DEEPX-AI'

inputs:
  token:
    description: 'GitHub token with repository write access'
    required: true
  target-repos:
    description: 'Comma-separated list of target repositories (e.g., "DEEPX-AI/do-dx_rt,DEEPX-AI/do-dx_app")'
    required: true
  source-branch:
    description: 'Source branch to merge from'
    required: false
    default: 'staging'
  target-branch:
    description: 'Target branch to merge into'
    required: false
    default: 'main'
  commit-message:
    description: 'Squash merge commit message template'
    required: false
    default: 'chore: squash merge {source} into {target}'
  delete-source-branch:
    description: 'Delete source branch after successful merge'
    required: false
    default: 'false'
  create-release:
    description: 'Create a release after successful merge'
    required: false
    default: 'false'

outputs:
  merged-repos:
    description: 'List of repositories that were successfully merged'
    value: ${{ steps.squash-merge.outputs.merged-repos }}
  success-count:
    description: 'Number of successfully merged repositories'
    value: ${{ steps.squash-merge.outputs.success-count }}
  failed-repos:
    description: 'List of repositories that failed to merge'
    value: ${{ steps.squash-merge.outputs.failed-repos }}
  merge-summary:
    description: 'Detailed merge summary'
    value: ${{ steps.squash-merge.outputs.merge-summary }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Execute Squash Merge
      id: squash-merge
      shell: bash
      run: |
        node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET_REPOS: ${{ inputs.target-repos }}
        INPUT_SOURCE_BRANCH: ${{ inputs.source-branch }}
        INPUT_TARGET_BRANCH: ${{ inputs.target-branch }}
        INPUT_COMMIT_MESSAGE: ${{ inputs.commit-message }}
        INPUT_DELETE_SOURCE_BRANCH: ${{ inputs.delete-source-branch }}
        INPUT_CREATE_RELEASE: ${{ inputs.create-release }}

branding:
  icon: 'git-merge'
  color: 'purple'
