name: 'Squash Merge Action'
description: 'Performs squash merge from source branch to target branch across multiple repositories'
author: 'DEEPX-AI'

inputs:
  token:
    description: 'GitHub token with repository write access'
    required: true
  target_repos:
    description: 'Comma-separated list of target repositories (e.g., "DEEPX-AI/do-dx_rt,DEEPX-AI/do-dx_app")'
    required: true
  source_branch:
    description: 'Source branch to merge from'
    required: false
    default: 'staging'
  target_branch:
    description: 'Target branch to merge into'
    required: false
    default: 'main'
  delete_source_branch:
    description: 'Delete source branch after successful merge'
    required: false
    default: 'false'
  create_release:
    description: 'Create a release after successful merge'
    required: false
    default: 'false'

outputs:
  merged_repos:
    description: 'List of repositories that were successfully merged'
    value: ${{ steps.squash-merge.outputs.merged_repos }}
  success_count:
    description: 'Number of successfully merged repositories'
    value: ${{ steps.squash-merge.outputs.success_count }}
  failed_repos:
    description: 'List of repositories that failed to merge'
    value: ${{ steps.squash-merge.outputs.failed_repos }}
  merge_summary:
    description: 'Detailed merge summary'
    value: ${{ steps.squash-merge.outputs.merge_summary }}
  highest_bump_type:
    description: 'Highest Bump Type among target repositories'
    value: ${{ steps.squash-merge.outputs.highest_bump_type }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Execute Squash Merge
      id: squash-merge
      shell: bash
      run: |
        node ${{ github.action_path }}/dist/index.js
      env:
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TARGET_REPOS: ${{ inputs.target_repos }}
        INPUT_SOURCE_BRANCH: ${{ inputs.source_branch }}
        INPUT_TARGET_BRANCH: ${{ inputs.target_branch }}
        INPUT_DELETE_SOURCE_BRANCH: ${{ inputs.delete_source_branch }}
        INPUT_CREATE_RELEASE: ${{ inputs.create_release }}

branding:
  icon: 'git-merge'
  color: 'purple'
